-- Q1. what is the total revenue generated by male vs female customers
select sum(purchase_amount) as total_revenue, gender
from customer 
group by gender

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount from customer
where discount_applied = 'Yes' and 
purchase_amount > (select avg(purchase_amount)from customer);

-- Q3. which are the top 5 products with highest average review rating
select item_purchased, ROUND(avg(review_rating::numeric),2) as avg_rating 
from customer
group by item_purchased
order by avg_rating DESC limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select ROUND(Avg(purchase_amount),2)as Average_amount, shipping_type 
from customer
where shipping_type IN ('Express', 'Standard')
group by shipping_type;

-- Q5.Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,  count(customer_id)as total_customers, 
ROUND(avg(purchase_amount),2) as avg_spends,
sum(purchase_amount) as total_spends
from customer
group by subscription_status ;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?”
select item_purchased, 
round(100.0 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2)  as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous 
-- purchases, and show the count of each segment.
with customer_type as
(select customer_id,previous_purchases,
case when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
Else 'Loyal'
End as customer_segment from customer)
select customer_segment, count(*) as number_of_customers
from customer_type
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category?
with item_count as 
(
select category, item_purchased, count(customer_id) as total_orders,
Row_number() over(Partition by category order by count(customer_id)Desc) as item_rank
from customer
group by category,item_purchased) 
select category, item_purchased, total_orders, item_rank
from item_count 
where item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select count(customer.customer_id)as total_customer, subscription_status from customer
where previous_purchases > 5 
group by subscription_status

-- “Q10. What is the revenue contribution of each age group?
select sum(purchase_amount)as total_revenue , age_group
from customer
group by age_group
order by total_revenue Desc
